# Generated by Django 4.2 on 2023-04-22 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Documento'), ('location', 'Ubicación'), ('button', 'Boton'), ('list', 'Lista')], default='text', max_length=50)),
                ('origin', models.CharField(choices=[('user', 'Usuario'), ('contact', 'Contacto')], max_length=50)),
            ],
        ),
    ]
