# Generated by Django 4.2.1 on 2023-06-02 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_rename_contact_message_contact_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='isGroupChat',
            new_name='is_group_chat',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='latestMessage',
            new_name='last_message',
        ),
    ]
