# Generated by Django 4.2.1 on 2023-06-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_user_contact_user_id_contact_channel_id'),
        ('message', '0006_chat_created_chat_updated_message_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='contact_id',
            field=models.ManyToManyField(related_name='chat_contacts', to='contact.contact'),
        ),
    ]
