# Generated by Django 4.2.1 on 2023-06-11 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_user_contact_user_id_contact_channel_id'),
        ('message', '0007_alter_chat_contact_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='contact_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='contact_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='contact.contact'),
            preserve_default=False,
        ),
    ]
