# Generated by Django 4.2.1 on 2023-06-02 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
        ('contact', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='channel_id',
            field=models.ForeignKey(default=854654564, on_delete=django.db.models.deletion.CASCADE, to='channel.channel'),
            preserve_default=False,
        ),
    ]
