# Generated by Django 4.2.1 on 2023-06-02 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('True', 'Activo'), ('False', 'Desactivar')], default=True, max_length=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canales',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('secret_key', models.CharField(max_length=300)),
                ('token', models.CharField(max_length=300)),
                ('url_id', models.CharField(max_length=300)),
                ('version', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('True', 'Activo'), ('False', 'Desactivar')], default=True, max_length=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('channel_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='channel.channel')),
            ],
        ),
    ]
