# Generated by Django 4.2.1 on 2023-05-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_whatsapptokens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsapptokens',
            old_name='whatsapp_toke',
            new_name='secret_key',
        ),
        migrations.RemoveField(
            model_name='whatsapptokens',
            name='channel_toke',
        ),
        migrations.AddField(
            model_name='whatsapptokens',
            name='token',
            field=models.CharField(default=12, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsapptokens',
            name='url_id',
            field=models.CharField(default=21, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsapptokens',
            name='version',
            field=models.CharField(default=12, max_length=300),
            preserve_default=False,
        ),
    ]
