# Generated by Django 4.2.1 on 2023-06-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_rename_contact_message_contact_id_and_more'),
        ('user', '0003_rename_whatsapp_toke_whatsapptokens_secret_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsapptokens',
            name='channel',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='avatar',
            field=models.CharField(default='https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg', max_length=500),
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='WhatsAppTokens',
        ),
    ]
